### ISSUE TITLE
mint() throwing ContractLogicError

### ISSUE THREAD

**Issue by eabdelmoneim** [thirdweb-dev/python-sdk#44]
Sundial:

![Screen Shot 2022-01-20 at 1 22 19 PM](https://user-images.githubusercontent.com/10700302/150408906-13bfc27a-e723-4e47-b56a-afa92b4b87ff.png)

**Comment by hammerchu** [comment]
just wonder if it's been fixed? because I still gave the "thirdweb_web3.exceptions.ContractLogicError: execution reverted" on currency_module.mint.

**Comment by jakeloo** [comment]
@hammerchu hey, check out the latest version of the python-sdk, it should be fixed now.
